server:
  port: 8081 # 应用程序启动端口

spring:
  application:
    name: springboot-microservice-demo # 应用程序名称
  # 配置数据源
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://10.20.1.182:3306/microservice?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  # 配置JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  # 配置数据库版本管理
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

# 应用程序日志配置
logging:
  config: classpath:log/file-logging-config.xml # 日志配置文件

logback:
  dir: logfile # 日志文件输出路径




