server:
  port: 8081 # 应用程序启动端口

spring:
  application:
    name: springboot-microservice-demo # 应用程序名称
  # 配置数据源
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://10.20.1.182:3306/microservice?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  # 配置JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  # 配置数据库版本管理
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

# 应用程序API接口文档配置
# 基础信息配置
swagger:
  enabled: true
  title: springboot-microservice-demo
  description: springboot 微服务项目
  version: 1.0.0-SNAPSHOT
  base-package: com.springboot.microservice.demo
  # 增加全局配置参数
  # global-operation-parameters[0]:
#    name: access_token
#    description: user access token
#    modelRef: string
#    parameterType: header
#    required: true
#  global-operation-parameters[1]:
#    name: timestamp
#    description: access timestamp
#    modelRef: int
#    parameterType: header
#    required: false
#  # 通用返回错误配置
#  apply-default-response-messages: true
#  global-response-message.get[0]:
#      code: 401
#      message: 401错误
#  global-response-message.get[1]:
#      code: 500
#      message: 服务器错误

# 应用程序日志配置
logging:
  config: classpath:log/file-logging-config.xml # 日志配置文件
logback:
  dir: logfile # 日志文件输出路径

# Keycloak Configuration
keycloak:
  auth-server-url: http://keycloak.10.20.1.72.nip.io/auth
  realm: SpringBootKeycloak
  resource: login-app
  credentials:
    secret: 6a2d7ae1-390b-4769-9f7e-45a649b72368
  principal-attribute: preferred_username


