-- ----------------------------
-- Records of metrics
-- ----------------------------
INSERT INTO `metrics` VALUES (1, '已连接客户端数', 'redis_connected_clients', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (2, 'keyspace击中总数', 'redis_keyspace_hits_total', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (3, '命令执行的次数总和', 'redis_command_call_duration_seconds_count', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (4, '系统耗费的cpu', 'redis_used_cpu_sys', NULL, 1, '资源', 0, NULL, 0);
INSERT INTO `metrics` VALUES (5, '使用的内存字节数', 'redis_memory_used_bytes', 'k', 1, '资源', 0, NULL, 0);
INSERT INTO `metrics` VALUES (6, '网络输入字节数', 'redis_net_input_bytes_total', 'k', 1, '资源', 0, NULL, 0);
INSERT INTO `metrics` VALUES (7, '网络输出字节数', 'redis_net_output_bytes_total', 'k', 1, '资源', 0, NULL, 0);
INSERT INTO `metrics` VALUES (8, '网络输出字节数', 'redis_net_output_bytes_total', 'k', 1, '资源', 0, NULL, 0);
INSERT INTO `metrics` VALUES (9, '当前连接客户端中最长的输出列表', 'redis_client_longest_output_list', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (10, '正在等待阻塞命令的客户端的数量', 'redis_blocked_clients', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (11, '当前连接客户端中最大输入缓存', 'redis_client_biggest_input_buf', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (12, '已连接的从服务器数量', 'redis_connected_slaves', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (13, 'master记录的复制偏移量', 'redis_master_repl_offset', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (14, 'buffer的大小', 'redis_replication_backlog_bytes', 'M', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (15, 'db中key的数量', 'redis_db_keys', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (16, 'db中过期的key', 'redis_db_keys_expiring', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (17, '键到期的平均剩余时间', 'redis_db_avg_ttl_seconds', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (18, '服务器是否正在载入文件', 'redis_loading_dump_file', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (19, '距离最近一次成功创建持久化文件时间', 'redis_rdb_changes_since_last_save', 's', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (20, '当前服务器正在创建 RDB 文件已经耗费的秒数', 'redis_rdb_current_bgsave_duration_sec', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (21, '最近一次创建 RDB 文件耗费的秒数', 'redis_rdb_last_bgsave_duration_sec', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (22, '当前服务器正在创建AOF文件已经耗费的秒数', 'redis_aof_current_rewrite_duration_sec', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (23, '最近一次创建AOF文件耗费的秒数', 'redis_aof_last_rewrite_duration_sec', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (27, '因为最大内存容量限制而被驱逐（evict）的键数量', 'redis_evicted_keys_total', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (28, '因为过期而被自动删除的数据库键数量', 'redis_expired_keys_total', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (29, '被订阅的频道数量', 'redis_pubsub_channels', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (30, '被订阅的模式数量', 'redis_pubsub_patterns', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (31, '最近一次 fork() 操作耗费的微秒数', 'redis_latest_fork_usec', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (33, '查找存储库键失败的次数', 'redis_keyspace_misses_total', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (34, '服务器已接受的连接请求数量', 'redis_connections_received_total', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (35, '服务器已执行的命令数量', 'redis_commands_processed_total', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (36, '服务器每秒钟执行的命令数量', 'redis_instantaneous_ops_per_sec', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (37, '输入带宽', 'redis_instantaneous_input_kbps', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (38, '输出带宽', 'redis_instantaneous_output_kbps', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (39, '因为最大客户端数量限制而被拒绝的连接请求数量', 'redis_rejected_connections_total', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (40, '命令执行的次数', 'redis_command_call_duration_seconds_count', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (41, '命令执行总和', 'redis_command_call_duration_seconds_sum', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (42, 'used_memory_rss 和 used_memory 之间的比率', 'redis_memory_fragmentation_ratio', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (43, '最大内存总量', 'redis_memory_max_bytes', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (44, 'Redis分配的内存总量', 'redis_memory_used_bytes', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (45, 'Lua 引擎所使用的内存大小', 'redis_memory_used_lua_bytes', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (46, 'Redis 的内存消耗极限值', 'redis_memory_used_peak_bytes', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (47, 'Redis 已分配的内存总量', 'redis_memory_used_rss_bytes', 'M', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (48, '服后台进程耗费的系统 CPU', 'redis_used_cpu_sys_children', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (49, '后台进程耗费的用户 CPU', 'redis_used_cpu_user_children', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (50, 'Redis 服务器耗费的用户 CPU', 'redis_used_cpu_user', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (51, '一个标志值，记录集群功能是否已经开启', 'redis_cluster_enabled', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (52, '最大内存', 'redis_config_maxmemory', NULL, 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (53, '最大客户端数', 'redis_config_maxclients', 'k', 1, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (101, '粗略估计的一个数据大小', 'zk_approximate_data_size', 'k', 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (102, '响应一个客户端请求的平均延迟时间', 'zk_avg_latency', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (103, '临时节点数', 'zk_ephemerals_count', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (104, '最大文件描述符数', 'zk_max_file_descriptor_count', 'k', 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (105, '响应一个客户端请求的最大延迟时间', 'zk_max_latency', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (106, '响应一个客户端请求的最小延迟时间', 'zk_min_latency', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (107, '活跃的连接数', 'zk_num_alive_connections', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (108, '打开文件的数量', 'zk_open_file_descriptor_count', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (109, '未完成客户端请求数', 'zk_outstanding_requests', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (110, '接收到客户端请求的包数量', 'zk_packets_received', 'k', 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (111, '发送给客户端的包数量', 'zk_packets_sent', 'k', 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (113, '是否检测到服务', 'zk_up', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (114, 'watchs的数量', 'zk_watch_count', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (115, 'znodes的数量', 'zk_znode_count', NULL, 2, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (116, 'broker数', 'kafka_brokers', NULL, 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (117, 'topic的partition数', 'kafka_topic_partitions', NULL, 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (118, 'topic的partition当前的偏移量', 'kafka_topic_partition_current_offset', 'k', 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (119, 'topic的partition最久的偏移量', 'kafka_topic_partition_oldest_offset', NULL, 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (120, 'topic的partition当前活跃的副本数量', 'kafka_topic_partition_in_sync_replica', NULL, 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (121, 'topic的partition负责读写指定分区的节点', 'kafka_topic_partition_leader', 'k', 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (122, 'topic的partition选出的leader是否优先', 'kafka_topic_partition_leader_is_preferred', NULL, 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (123, 'topic的partition的副本数', 'kafka_topic_partition_replicas', NULL, 3, '性能', 0, NULL, 0);
INSERT INTO `metrics` VALUES (124, '在副本partition下的topic的partition', 'kafka_topic_partition_under_replicated_partition', NULL, 3, '性能', 0, NULL, 0);

SET FOREIGN_KEY_CHECKS = 1;